### ISSUE TITLE
Finalize test data for CI pipeline

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-online#19]
**Acceptance Criteria:**
- Test data must be approved as 'safe' for inclusion, possibly when encrypted, in the public fecfile-online repository by FEC.
- The Circle CI configuration must be updated to load the test data before running unit tests
- The docker-compose development environment should default to loading the test data when first instantiated
- If encryption is required, decryption keys must be stored in an environment variable if stored at all
- If encryption is required, Instructions for use in the development system and Circle CI should be included in the fecfile-online/db/README.md file

**Comment by WiseQA** [comment]
As noted no QA action required on this ticket - moved to closed as ticket complete.
